version: "2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "8080:8080"
